### PR TITLE
CI generated online documentation

### PR DESCRIPTION
**Pull request by anchal-physics**
Workflow has been added to generate documentation and deplot to gh-pages whenever a new release with a version number is generated (goes to stable documentation) and when master branch is updated with a push or PR.

### CODE REVIEW

**Comment by orso82** [comment]
This works! Thank you so much @anchal-physics !!

**Comment by anchal-physics** [comment]
You're welcome. Please note that [stable online documentation](https://projecttorreypines.github.io/IMASDD.jl/stable) would only be generated once you create a tagged release with version number. Currently this link on the README page is broken.

**Comment by anchal-physics** [comment]
No, I can not publish them to Julia registry yet since IMASDD is a dependency and it is not available at Julia registry. So I need IMASDD published before I can publish other packages.

**Comment by orso82** [comment]
Let's publish all of them then. Have you looked into how that works? I have not.

**Comment by anchal-physics** [comment]
Yesh, I have. You need to install [registrator](https://github.com/JuliaRegistries/Registrator.jl) bot to your repository which are a few clicks. Then open a new issue and comment following to it:
```
@JuliaRegistrator register()
```

I have already tried it on https://github.com/ProjectTorreyPines/GGDUtils.jl/issues/47 and that's how I know that IMASDD needs to be registered first.

source: https://julialang.org/contribute/developing_package/#step_5_register_your_package

**Pull request merged**
